[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers - OWASP Best Practices
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Permitted-Cross-Domain-Policies = "none"
    
    # HSTS - Force HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy - Strict CSP
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://*.supabase.co;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: blob: https://*.supabase.co https://*.supabase.in https://img.shields.io https://avatars.githubusercontent.com;
      connect-src 'self' https://*.supabase.co https://*.supabase.in wss://*.supabase.co wss://*.supabase.in https://api.github.com https://checkpoint-api.hashicorp.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
      block-all-mixed-content;
    """
    
    # Permissions Policy - Restrict browser features
    Permissions-Policy = """
      accelerometer=(),
      camera=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      payment=(),
      usb=()
    """
    
    # Additional Security Headers
    X-DNS-Prefetch-Control = "off"
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"
    
    # Cache Control for Security
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

# Specific headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for service worker (if any)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
